# Generated by Django 3.2.7 on 2021-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=60)),
                ('contents', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=200)),
                ('like_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('upload_date', models.DateField(auto_now=True)),
                ('file_img', models.ImageField(default='default_image.jpeg', upload_to='')),
                ('file_name', models.CharField(max_length=1000)),
                ('hashtag', models.CharField(max_length=1000)),
            ],
        ),
    ]
