# Generated by Django 3.2.8 on 2021-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_email', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=60)),
                ('contents', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=200)),
                ('like_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('upload_date', models.DateField(auto_now=True)),
                ('file_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
