# Generated by Django 3.2.8 on 2021-11-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='favorite',
            new_name='favorite_artist',
        ),
    ]
