# Generated by Django 3.2.7 on 2021-11-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0002_artwork_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_view_list', to='artworks.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
