# Generated by Django 3.2.8 on 2021-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20211103_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_email',
            field=models.EmailField(max_length=40),
        ),
    ]
