# Generated by Django 3.2.8 on 2021-11-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_rename_favorite_artwork_favorite_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='favorite_artist',
        ),
    ]
