# Generated by Django 3.2.8 on 2021-10-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20211027_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='file_img',
            field=models.CharField(default='../img/img_v.jpg', max_length=1000),
        ),
    ]
