# Generated by Django 3.2.8 on 2021-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_file_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file_img',
            field=models.ImageField(blank=True, height_field='None', max_length='None', null=True, upload_to='None', width_field='None'),
        ),
    ]
