# Generated by Django 3.2.8 on 2021-10-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_alter_artwork_file_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file_img',
            field=models.ImageField(default='localhost:8000/img/img_v.png', upload_to=''),
        ),
    ]
