# Generated by Django 3.2.7 on 2021-11-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_addr', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('birthday', models.CharField(max_length=10)),
            ],
        ),
    ]
