# Generated by Django 3.2.8 on 2021-10-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.CharField(max_length=40)),
                ('pwd', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('birthday', models.CharField(max_length=10)),
            ],
        ),
    ]
