# Generated by Django 3.2.8 on 2021-10-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_addr',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
