# Generated by Django 3.2.8 on 2021-11-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211110_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='artist_level',
            field=models.CharField(default='nov', max_length=100, null=True),
        ),
    ]
