# Generated by Django 3.2.8 on 2021-11-29 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteArtist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artist_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
