# Generated by Django 3.2.8 on 2021-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='artist_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Specified')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
