# Generated by Django 3.2.8 on 2021-11-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_artist_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
