# Generated by Django 3.2.8 on 2021-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(choices=[('NS', 'Not Selected'), ('M', 'Male'), ('F', 'Female')], default='NS', max_length=10)),
                ('artist_level', models.CharField(choices=[('pro', 'Professional'), ('adv', 'Advanced'), ('nov', 'Novice')], default='nov', max_length=10)),
                ('join_date', models.DateField(auto_now=True)),
                ('revenue', models.IntegerField(default=0)),
            ],
        ),
    ]
